import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/综艺/塔摩利中居之在便利店买也无妨.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E5%A1%94%E6%91%A9%E5%88%A9%E4%B8%AD%E5%B1%85%E4%B9%8B%E5%9C%A8%E4%BE%BF%E5%88%A9%E5%BA%97%E4%B9%B0%E4%B9%9F%E6%97%A0%E5%A6%A8.html\",\"title\":\"2012 - 塔摩利・中居之在便利店买也无妨\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"2012 - 塔摩利・中居之在便利店买也无妨\",\"icon\":\"caret-up\",\"description\":\"综艺 剧集名：塔摩利・中居之在便利店买也无妨 タイトル：タモリ・中居のコンビニでイイのに! ​​​？ 上映日期：2012-04-09 电视台：富士电视台|フジテレビ 集数：1 官网: 本剧集官网 简介：第2弾。今回は生放送形式に戻った。総合司会のタモリと中居が主催するお花見の会場に2012年春から放送が開始される、新ドラマ出演者（このクールから「土23...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E5%A1%94%E6%91%A9%E5%88%A9%E4%B8%AD%E5%B1%85%E4%B9%8B%E5%9C%A8%E4%BE%BF%E5%88%A9%E5%BA%97%E4%B9%B0%E4%B9%9F%E6%97%A0%E5%A6%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2012 - 塔摩利・中居之在便利店买也无妨\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"综艺 剧集名：塔摩利・中居之在便利店买也无妨 タイトル：タモリ・中居のコンビニでイイのに! ​​​？ 上映日期：2012-04-09 电视台：富士电视台|フジテレビ 集数：1 官网: 本剧集官网 简介：第2弾。今回は生放送形式に戻った。総合司会のタモリと中居が主催するお花見の会場に2012年春から放送が開始される、新ドラマ出演者（このクールから「土23...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/other/2012ddzg.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2012 - 塔摩利・中居之在便利店买也无妨\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/other/2012ddzg.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.57,\"words\":170},\"filePathRelative\":\"🎥其他/综艺/塔摩利中居之在便利店买也无妨.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
