import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/综艺/忍俊不禁の吉卜力工作室密着.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E5%BF%8D%E4%BF%8A%E4%B8%8D%E7%A6%81%E3%81%AE%E5%90%89%E5%8D%9C%E5%8A%9B%E5%B7%A5%E4%BD%9C%E5%AE%A4%E5%AF%86%E7%9D%80.html\",\"title\":\"2013 - 「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"2013 - 「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP\",\"icon\":\"caret-up\",\"description\":\"综艺 剧集名：「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP タイトル：「笑ってコラえて！」とスタジオジブリが完全コラボレーション。 宮崎駿監督 最新作『風立ちぬ』に密着取材した３時間スペシャル。 上映日期：2013-07-10 电视台：日本电视台|NTV 集数：1 官网： 失效 简介：揭秘最新作品「起风了」的幕后故事！挖掘宫崎骏导...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E5%BF%8D%E4%BF%8A%E4%B8%8D%E7%A6%81%E3%81%AE%E5%90%89%E5%8D%9C%E5%8A%9B%E5%B7%A5%E4%BD%9C%E5%AE%A4%E5%AF%86%E7%9D%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2013 - 「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"综艺 剧集名：「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP タイトル：「笑ってコラえて！」とスタジオジブリが完全コラボレーション。 宮崎駿監督 最新作『風立ちぬ』に密着取材した３時間スペシャル。 上映日期：2013-07-10 电视台：日本电视台|NTV 集数：1 官网： 失效 简介：揭秘最新作品「起风了」的幕后故事！挖掘宫崎骏导...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/other/2013jpl.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2013 - 「起风了」映前宣番～1亿人大质问！？忍俊不禁の吉卜力工作室密着SP\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/other/2013jpl.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.59,\"words\":177},\"filePathRelative\":\"🎥其他/综艺/忍俊不禁の吉卜力工作室密着.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
