import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/综艺/未詳事件特別対策係事件簿花絮制作.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E6%9C%AA%E8%A9%B3%E4%BA%8B%E4%BB%B6%E7%89%B9%E5%88%A5%E5%AF%BE%E7%AD%96%E4%BF%82%E4%BA%8B%E4%BB%B6%E7%B0%BF%E8%8A%B1%E7%B5%AE%E5%88%B6%E4%BD%9C.html\",\"title\":\"2013 - SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"2013 - SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作\",\"icon\":\"caret-up\",\"description\":\"综艺 剧集名：SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作 タイトル：SPEC〜零〜／警視庁公安部公安第五課 未詳事件特別対策係事件簿 上映日期：2013-10-23 电视台：TBS 集数：1 官网： 失效 简介： #零#的后期制作花絮，本次SP新增哪些人物呢，他们的SPEC是什么呢？户田惠梨香X加濑亮的温馨对谈，还有其他不...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%E7%BB%BC%E8%89%BA/%E6%9C%AA%E8%A9%B3%E4%BA%8B%E4%BB%B6%E7%89%B9%E5%88%A5%E5%AF%BE%E7%AD%96%E4%BF%82%E4%BA%8B%E4%BB%B6%E7%B0%BF%E8%8A%B1%E7%B5%AE%E5%88%B6%E4%BD%9C.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2013 - SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"综艺 剧集名：SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作 タイトル：SPEC〜零〜／警視庁公安部公安第五課 未詳事件特別対策係事件簿 上映日期：2013-10-23 电视台：TBS 集数：1 官网： 失效 简介： #零#的后期制作花絮，本次SP新增哪些人物呢，他们的SPEC是什么呢？户田惠梨香X加濑亮的温馨对谈，还有其他不...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/other/2013spec.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2013 - SPEC警視庁公安部公安第五課 未詳事件特別対策係事件簿-零-.花絮制作\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/other/2013spec.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.56,\"words\":168},\"filePathRelative\":\"🎥其他/综艺/未詳事件特別対策係事件簿花絮制作.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
