import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎬sp/🎬2012及之前/在山脊的那一边父与子的日航飞机坠落事件.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%ACsp/%F0%9F%8E%AC2012%E5%8F%8A%E4%B9%8B%E5%89%8D/%E5%9C%A8%E5%B1%B1%E8%84%8A%E7%9A%84%E9%82%A3%E4%B8%80%E8%BE%B9%E7%88%B6%E4%B8%8E%E5%AD%90%E7%9A%84%E6%97%A5%E8%88%AA%E9%A3%9E%E6%9C%BA%E5%9D%A0%E8%90%BD%E4%BA%8B%E4%BB%B6.html\",\"title\":\"在山脊的那一边～父与子的日航飞机坠落事件～\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"在山脊的那一边～父与子的日航飞机坠落事件～\",\"icon\":\"caret-up\",\"description\":\"剧集名：在山脊的那一边～父与子的日航飞机坠落事件～ タイトル：尾根のかなたに〜父と息子の日航機墜落事故〜 电视台：WOWOW 播放日期：2012-10-07 集数：2 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：27年前，这里埋葬了520名鲜活的生命，一场空难，将所有人的命运联系在了一起。27年后的人们，是带着怎样的心情生活 ？27年后的人们，是否...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%ACsp/%F0%9F%8E%AC2012%E5%8F%8A%E4%B9%8B%E5%89%8D/%E5%9C%A8%E5%B1%B1%E8%84%8A%E7%9A%84%E9%82%A3%E4%B8%80%E8%BE%B9%E7%88%B6%E4%B8%8E%E5%AD%90%E7%9A%84%E6%97%A5%E8%88%AA%E9%A3%9E%E6%9C%BA%E5%9D%A0%E8%90%BD%E4%BA%8B%E4%BB%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"在山脊的那一边～父与子的日航飞机坠落事件～\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"剧集名：在山脊的那一边～父与子的日航飞机坠落事件～ タイトル：尾根のかなたに〜父と息子の日航機墜落事故〜 电视台：WOWOW 播放日期：2012-10-07 集数：2 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：27年前，这里埋葬了520名鲜活的生命，一场空难，将所有人的命运联系在了一起。27年后的人们，是带着怎样的心情生活 ？27年后的人们，是否...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/sp/2012/2012zsjdnyb.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"在山脊的那一边～父与子的日航飞机坠落事件～\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/sp/2012/2012zsjdnyb.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.61,\"words\":182},\"filePathRelative\":\"🎬sp/🎬2012及之前/在山脊的那一边父与子的日航飞机坠落事件.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
