import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎬sp/🎬2012及之前/成为新娘的日子鸟羽答志岛天堂.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%ACsp/%F0%9F%8E%AC2012%E5%8F%8A%E4%B9%8B%E5%89%8D/%E6%88%90%E4%B8%BA%E6%96%B0%E5%A8%98%E7%9A%84%E6%97%A5%E5%AD%90%E9%B8%9F%E7%BE%BD%E7%AD%94%E5%BF%97%E5%B2%9B%E5%A4%A9%E5%A0%82.html\",\"title\":\"成为新娘的日子～鸟羽·答志岛天堂～\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"成为新娘的日子～鸟羽·答志岛天堂～\",\"icon\":\"caret-up\",\"description\":\"剧集名：成为新娘的日子～鸟羽·答志岛天堂～ タイトル：ヤアになる日～鳥羽・答志島パラダイス～ 电视台：NHK 播放日期：2012-09-30 集数：1 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：在鸟羽市内的酒店工作的山岡紗智子怀上了答志岛出身的鳴海久志的小孩。久志说要回答志岛做渔师。隐瞒了已有身孕的事，紗智子造访了这个小岛，然后…… ​​​ ca...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%ACsp/%F0%9F%8E%AC2012%E5%8F%8A%E4%B9%8B%E5%89%8D/%E6%88%90%E4%B8%BA%E6%96%B0%E5%A8%98%E7%9A%84%E6%97%A5%E5%AD%90%E9%B8%9F%E7%BE%BD%E7%AD%94%E5%BF%97%E5%B2%9B%E5%A4%A9%E5%A0%82.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"成为新娘的日子～鸟羽·答志岛天堂～\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"剧集名：成为新娘的日子～鸟羽·答志岛天堂～ タイトル：ヤアになる日～鳥羽・答志島パラダイス～ 电视台：NHK 播放日期：2012-09-30 集数：1 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：在鸟羽市内的酒店工作的山岡紗智子怀上了答志岛出身的鳴海久志的小孩。久志说要回答志岛做渔师。隐瞒了已有身孕的事，紗智子造访了这个小岛，然后…… ​​​ ca...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/sp/2012/2012cwxndrz.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"成为新娘的日子～鸟羽·答志岛天堂～\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/sp/2012/2012cwxndrz.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.52,\"words\":157},\"filePathRelative\":\"🎬sp/🎬2012及之前/成为新娘的日子鸟羽答志岛天堂.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
