import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/🐱岩合光昭的猫步走世界/岩合光昭的猫步走世界-SP.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C/%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-SP.html\",\"title\":\"岩合光昭的猫步走世界 - SP\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"岩合光昭的猫步走世界 - SP\",\"icon\":\"cat\",\"order\":6,\"description\":\"剧集名：岩合光昭的猫步走世界 - SP ドラマの番組名：岩合光昭の世界ネコ歩き スペシャル 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：本期开启话唠模式，岩合光昭与四位爱（mao）猫（奴）艺术家分享拍摄感想，以及如何把自家喵拍得萌萌哒窍门 cast：岩合光昭 / 坂本美雨 / 坂崎幸之助 / 谷山浩子 / 大贯妙子 / 猫猫们🐱 ...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C/%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-SP.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"岩合光昭的猫步走世界 - SP\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"剧集名：岩合光昭的猫步走世界 - SP ドラマの番組名：岩合光昭の世界ネコ歩き スペシャル 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：本期开启话唠模式，岩合光昭与四位爱（mao）猫（奴）艺术家分享拍摄感想，以及如何把自家喵拍得萌萌哒窍门 cast：岩合光昭 / 坂本美雨 / 坂崎幸之助 / 谷山浩子 / 大贯妙子 / 猫猫们🐱 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/maobu/mb11.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"岩合光昭的猫步走世界 - SP\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/maobu/mb11.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.49,\"words\":147},\"filePathRelative\":\"🎥其他/🐱岩合光昭的猫步走世界/岩合光昭的猫步走世界-SP.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
