import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/🐱岩合光昭的猫步走世界-停更/仕事流儀.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%81%9C%E6%9B%B4/%E4%BB%95%E4%BA%8B%E6%B5%81%E5%84%80.html\",\"title\":\"仕事の流儀 动物摄影师岩合光昭\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"仕事の流儀 动物摄影师岩合光昭\",\"icon\":\"cat\",\"order\":7,\"description\":\"剧集名：仕事の流儀 动物摄影师岩合光昭 タイトル：プロフェッショナル仕事の流儀 猫を知れば、世界が変わる 動物写真家・岩合光昭 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：岩合光昭66岁（2017年时），日本代表性动物摄影师。各种出版物、巡回写真展不断的他依然在新宿区小小的事务所里珍藏着半辈子拍下的动物胶片；早已声名鹊起的他依然为了...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%81%9C%E6%9B%B4/%E4%BB%95%E4%BA%8B%E6%B5%81%E5%84%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"仕事の流儀 动物摄影师岩合光昭\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"剧集名：仕事の流儀 动物摄影师岩合光昭 タイトル：プロフェッショナル仕事の流儀 猫を知れば、世界が変わる 動物写真家・岩合光昭 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：岩合光昭66岁（2017年时），日本代表性动物摄影师。各种出版物、巡回写真展不断的他依然在新宿区小小的事务所里珍藏着半辈子拍下的动物胶片；早已声名鹊起的他依然为了...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/maobu/mb2.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"仕事の流儀 动物摄影师岩合光昭\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/maobu/mb2.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.71,\"words\":214},\"filePathRelative\":\"🎥其他/🐱岩合光昭的猫步走世界-停更/仕事流儀.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
