import comp from "E:/tsgproject/list/tsg/src/.vuepress/.temp/pages/🎥其他/🐱岩合光昭的猫步走世界-停更/岩合光昭的猫步走世界-大洋洲.html.vue"
const data = JSON.parse("{\"path\":\"/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%81%9C%E6%9B%B4/%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%A4%A7%E6%B4%8B%E6%B4%B2.html\",\"title\":\"岩合光昭的猫步走世界 - 大洋洲\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"岩合光昭的猫步走世界 - 大洋洲\",\"icon\":\"cat\",\"order\":4,\"description\":\"剧集名：岩合光昭的猫步走世界 タイトル：岩合光昭の世界ネコ歩き 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：跟随岩合光昭，从猫的角度看世界，遍览世界各地。 cast：岩合光昭 / 猫猫们🐱 大洋洲： 澳大利亚墨尔本 旁白:山田孝之 简介：澳洲第二大城市墨尔本 老剧院的看板喵 美容院的卖萌喵 还有节目有史以来最高龄喵 话说澳洲喵巡逻...\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://weibo.com/u/2606228641/%F0%9F%8E%A5%E5%85%B6%E4%BB%96/%F0%9F%90%B1%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%81%9C%E6%9B%B4/%E5%B2%A9%E5%90%88%E5%85%89%E6%98%AD%E7%9A%84%E7%8C%AB%E6%AD%A5%E8%B5%B0%E4%B8%96%E7%95%8C-%E5%A4%A7%E6%B4%8B%E6%B4%B2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"三角小透明\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"岩合光昭的猫步走世界 - 大洋洲\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"剧集名：岩合光昭的猫步走世界 タイトル：岩合光昭の世界ネコ歩き 电视台：NHK 官网: 本剧集官网 豆瓣链接： 豆瓣主页 简介：跟随岩合光昭，从猫的角度看世界，遍览世界各地。 cast：岩合光昭 / 猫猫们🐱 大洋洲： 澳大利亚墨尔本 旁白:山田孝之 简介：澳洲第二大城市墨尔本 老剧院的看板喵 美容院的卖萌喵 还有节目有史以来最高龄喵 话说澳洲喵巡逻...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://listpic.tsgsanjiao.com/maobu/mb34.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"三角小透明\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"岩合光昭的猫步走世界 - 大洋洲\\\",\\\"image\\\":[\\\"https://listpic.tsgsanjiao.com/maobu/mb34.jpg\\\",\\\"https://listpic.tsgsanjiao.com/maobu/mb16.jpg\\\",\\\"https://listpic.tsgsanjiao.com/maobu/mb1.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"三角小透明\\\",\\\"url\\\":\\\"https://weibo.com/u/2606228641\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.67,\"words\":200},\"filePathRelative\":\"🎥其他/🐱岩合光昭的猫步走世界-停更/岩合光昭的猫步走世界-大洋洲.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
